backend:
  name: github
  repo: anvold95/av-a.no
  branch: av-a.no
  base_url: "https://av-a-oauth.vercel.app"
  auth_endpoint: "/api/auth"

media_folder: "img/projects"
public_folder: "/img/projects"

collections:
  - name: "innhold"
    label: "Innhold"
    files:
      - file: "content.json"   # må finnes på https://av-a.no/content.json
        label: "Tekst og innhold"
        name: "content"
        fields:
          - { label: "Tittel", name: "title", widget: "string" }
